- name: Apply environment
  apply:
    environment:
      OCI_CLI_AUTH: "instance_principal" # Used only for OCI

- name: Ensure oci oss bucket exists
  command: oci os bucket get --name {{ oss_bucket_name }} --auth instance_principal

- name: download files from oci oss bucket
  command: oci os object bulk-download -bn {{ oss_bucket_name }} --prefix {{ oss_path }} --dest-dir {{ local_file_or_folder_path }} --auth instance_principal
  async: 3600
  poll: 10